#!/usr/bin/env bash
# Install your load balancer
sudo apt-get -y update
sudo apt-get -y install haproxy
sudo chown  $USER:$USER /etc/haproxy/haproxy.cfg

echo "
frontend estebanweb
    bind *:80
    mode http
    default_backend app
backend app
    balance roundrobin
    server 17891-web-01 3.239.101.36:80 check
    server 17891-web-02 34.239.176.22:80 check" >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart
